$("#pract6").click(function(){
	$("#linearGradient").hide();
	$("#textShadow").hide();
	$("#multipleTransformation").hide();
	$("#animation").hide();
	$("#transitionDiv").show();


});
$("#pract7").click(function(){
	$("#textShadow").hide();
	$("#multipleTransformation").hide();
	$("#animation").hide();
	$("#transitionDiv").hide();
	$("#linearGradient").show();
});
$("#pract8").click(function(){
	$("#linearGradient").hide();
	$("#multipleTransformation").hide();
	$("#animation").hide();
	$("#transitionDiv").hide();
	$("#textShadow").show();
})
$("#pract9").click(function(){
	$("#linearGradient").hide();
	$("#textShadow").hide();
	$("#animation").hide();
	$("#transitionDiv").hide();
	$("#multipleTransformation").show();
})
$("#pract10").click(function(){
	$("#linearGradient").hide();
	$("#textShadow").hide();
	$("#multipleTransformation").hide();
	$("#transitionDiv").hide();
	$("#animation").show();
})